### ISSUE TITLE
node-sass no such file or directory

### ISSUE THREAD

**Issue by se77en** [moarwick/elm-webpack-starter#24] opened 2016-07-28 04:29 UTC
when I execute `npm start`, it shows this:

```
ERROR in ENOENT: no such file or directory, 
scandir '/Users/AriesDevil/Documents/workspace/elm_workspace/girion/node_modules/node-sass/vendor'
```

**Comment by ciaran-phillips** [comment] 2016-08-05 22:23
I had this error too and found others encountering it here: https://github.com/davezuko/react-redux-starter-kit/issues/791

I haven't investigated enough to know the root cause, but based on that thread I deleted my node-sass folder and manually reinstalled it (`npm install --save-dev node-sass`). That seemed to fix the issue for the moment (possibly because that bumped me up to node-sass 3.8.0 from 3.7.0)

**Comment by phoenleo** [comment] 2016-08-06 08:01
I can fix it after rebuild the node-sass using this command:

`npm rebuild node-sass`

This command will build the vendor folder.
FYI: I'm using node-sass version 3.8.0

**Comment by se77en** [comment] 2016-08-06 13:20
@ciaran-phillips @phoenleo thx~

**Comment by ciaran-phillips** [comment] 2016-08-09 18:41
Eh... not really sure this issue should be closed. We've got a workaround but I assume it's still a problem

Maybe @moarwick can weigh in

I'm not great with npm but if I get a chance in the next few days I can dig in a little and try to confirm it's just an issue with that version of node-sass. Hopefully I can submit a PR

**Comment by moarwick** [comment] 2016-08-10 17:05
ok, had a look.. i think we can close the issue. i pushed a minor update (a few updated packages) but most likely you had a node version mismatch. whenever you run into any such issues, reinstall all dependencies afresh:

```
    rm -rf node_modules
    npm i
```

hope it helps!

**Closed as completed** 2016-08-11 02:58 UTC
